<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The RESTEasy Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.resteasy.reproducer</groupId>
        <artifactId>resteasy-reproducer-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>resteasy-reproducer-wildfly</artifactId>
    <packaging>war</packaging>

    <name>RESTEasy Reproducer - WildFly</name>
    <description>WAR module for reproducing issues on WildFly</description>

    <properties>
        <version.org.wildfly.testing>1.0.0.Alpha5-SNAPSHOT</version.org.wildfly.testing>
        <version.wildfly-maven-plugin>6.0.1.Final</version.wildfly-maven-plugin>

        <!-- Intentionally left empty to ensure we use the latest version of WildFly -->
        <version.org.wildfly/>

        <!-- Test properties -->
        <jboss.home>${project.build.directory}${file.separator}wildfly</jboss.home>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.wildfly.testing</groupId>
                <artifactId>wildfly-testing-tools-bom</artifactId>
                <version>${version.org.wildfly.testing}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.logging</groupId>
                    <artifactId>jboss-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.wildfly.testing</groupId>
            <artifactId>wildfly-junit-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.wildfly.testing</groupId>
            <artifactId>wildfly-junit-extension</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <jboss.home>${jboss.home}</jboss.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>${version.wildfly-maven-plugin}</version>
                <configuration>
                    <jboss-home>${jboss.home}</jboss-home>
                    <provisioning-dir>${jboss.home}</provisioning-dir>
                    <feature-packs>
                        <feature-pack>
                            <groupId>org.wildfly</groupId>
                            <artifactId>wildfly-ee-galleon-pack</artifactId>
                            <version>${version.org.wildfly}</version>
                        </feature-pack>
                    </feature-packs>
                    <channels>
                        <channel>
                            <manifest>
                                <groupId>org.wildfly.channels</groupId>
                                <artifactId>wildfly-ee</artifactId>
                                <version>${version.org.wildfly}</version>
                            </manifest>
                        </channel>
                        <channel>
                            <manifest>
                                <groupId>org.jboss.resteasy.channels</groupId>
                                <artifactId>resteasy-7.0</artifactId>
                                <version>${version.org.jboss.resteasy}</version>
                            </manifest>
                        </channel>
                    </channels>
                    <galleon-options>
                        <jboss-fork-embedded>true</jboss-fork-embedded>
                    </galleon-options>
                </configuration>
                <executions>
                    <execution>
                        <id>provision-test-server</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>provision</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
